RUN_STRINGS = (
    "Ha? Ne? Kaçtılar mı?" ,
    "Şimdi beni görüyorsun, şimdi görmüyorsun."
    "ε = ε = ε = ε = ┌ (; ￣ ▽ ￣) ┘" ,
    "Buraya geri gel!" ,
    "REEEEEEEEEEEEEEEEEE !!!!!!!" ,
    "Duvara dikkat et!" ,
    "Beni onlarla yalnız bırakma !!" ,
    "Şirketiniz var!" ,
    "Chotto mat!" , # Ya iki Japon?
    "Yare yare şaşkınlık" ,
    "* Naruto run etkinleştirildi *" ,
    "* Nezuko çalıştırması etkinleştirildi *" ,
    "Hey, az önce yaptığın şey için sorumluluk al!" ,
    "Oranlar senin lehine olsun." ,
    "Herkesi yönet , bomba bıraktılar 💣💣" ,
    "Ve sonsuza kadar kayboldular, bir daha asla görülmeyecekler." ,
    "Efsaneye göre, hala koşuyorlar." ,
    "Görüşürüz bebeğim." ,
    "Ah, ne büyük bir israf. Bunu sevdim." ,
    "Doktor'un dediği gibi ... RUN!" ,
)

SLAP_SAITAMA_TEMPLATES  = (
    "Beni bir kez daha tokatla ve ben seni sustururum." ,
    "Beni tokatlamayı kes. REEEEEEEEEEEEEE." ,
    [
        "Seni bir dakikalığına susturuyorum." ,   # normal cevap
        "Seni susturmadığım için beni tokatlamayı kes. REEEEEEEEEE.",  # reply to admin
        "tmute"  # command
    ]
)

SLAP_TEMPLATES = (
  "{user2}, {user1} tarafından çekildi.",
    "{user2}, {user1} 'dan kaçmaya çalışırken bir kaktüsün içine girdi.",
    "{user1}, {user1} 'dan kaçmaya çalışırken boğuldu.",
    "{user2} bir kaktüs yamacına düştü.",
    "{user2} alev aldı.",
    "{user2} hassas bir şekilde yandı.",
    "{user2}, {user1} ile savaşırken net bir şekilde yakıldı.",
    "{user2} şimşek çarptı.",
    "{user2}, {user1} tarafından katledildi.",
    "{user2} sihirle öldürüldü.",
    "{user2} pats olmadan aç kaldı.",
    "{user2} dünyadan düştü.",
    "{user2}, {user1} tarafından geçersiz kılındı.",
    "{user2} 'ın kemikleri ıssız rüzgarla temiz kazınmış.",
    "{user2} bayıldı.",
    "{user2} kullanılabilir Pokemon dışında! {user2} beyazladı !.",
    "{user2} kullanılabilir Pokemon dışında! {user2} karartıldı!",
    "{user2} bu acımasız dünyaya veda ediyor.",
    "{user2} rekt aldı.",
    "{user2}, {user1} tarafından ikiye ayrıldı.",
    "{user2} 'ın kavunu {user1} tarafından bölündü.",
    "{user2}, {user1} tarafından dilimlenmiş ve doğranmış.",
    "{user2}, {user1} 'in gizemli tropikal hastalığından öldü.",
    "{user2} el bombası ile sıcak patates oynadı.",
    "{user2}, {user1} tarafından bıçaklandı.",
    "{user2} bir el bombası yedi.",
    "{user2} akşam yemeğinde ne var!",
    "{user2}, {user1} tarafından sonlandırıldı.",
    "{user2} bir uçaktan atılmadan önce vuruldu.",
    "{user2} bir hatayla karşılaştı.",
    "{user2} öldü ve bir keçi olarak reenkarne edildi.",
    "{user1}, {user2} bir binayı attı.",
    "{user2} erken gömüldü.",
    "{user1} {user2} adlı kullanıcının e-postasını spam etti.",
    "{user1} küçük, yıldızlararası bir uzay gemisiyle {user2} 'yi vurdu.",
    "{user1} {user2} 'ı check-mat'a koy.",
    "{user1} RSA şifreli {user2} ve özel anahtarı sildi.",
    "{user1} {user2} 'ı arkadaş alanına yerleştirin.",
    "{user1}, bir DMCA yayından kaldırma isteğiyle {user2} tokatlıyor!",
    "{user2} hastane kangreninden öldü.",
    "{user2}, {user1} Doktorundan bir ev çağrısı aldı.",
    "{user1} kafalı {user2}.",
    "{user2} öfkeli bir grup tarafından taşlandı.",
    "{user1}, {user2} kullanıcısına dava açtı.",
    "{user2}, {user1} tarafından bir kez tıklandı.",
    "{user1}, bellek deliğinden {user2} gönderdi.",
    "{user2} bir hataydı. - '{user1}'",
    "{user1} {user2} iki hamlede kontrol edildi.",
    "{user2} gereksiz hale getirildi.",
    "bir sopa ile {{user1} {hits} {user2}!",
    "bir Taijutsu Vuruşu ile {{user1} {hits} {user2}!",
    "X-Gloves ile {{user1} {hits} {user2}!",
    "bir Jet Punch ile {{user1} {hits} {user2}.",
    "Bir Jet Tabanca ile {user1} {hits} {user2}!",
    "Amerika Birleşik Devletleri'nde Smash! ile {user1} {hits} {user2}.",
   "Detroit Smash ile {user1} {hits} {user2}!",
    "Texas Smash ile {{user1} {hits} {user2}!",
    "California Smash ile {{user1} {hits} {user2}!",
    "Yeni Hampshire Şutu ile {user1} {hits} {user2}!",
    "Bir Missouri Smash ile {{user1} {hits} {user2}!",
    "bir Carolina Smash ile {{user1} {hits} {user2}.",
    "Bir King Kong Silahı ile {user1} {hits} {user2}!",
    "bir beysbol sopası olan {user1} {hits} {user2}. metal..",
    "* Ciddi yumruklar {user2} *.",
    "* Normal zımbalar {user2} *.",
    "* Ardışık Normal yumruklar {user2} *.",
    "* İki Elle Ardışık Normal Zımba {user2} *.",
    "* Onların utançtan ölmelerine izin vermek için {user2} 'ı yok sayar.",
    "* {user2} 'a işaret ediyor * Bu küstahlık nedir ... kayıp çocuk?"
    "* Bir Yangın Kasırgası ile {user2} tuşuna basar.",
    "{user1} {user2} 'i göze çarpıyor!",
    "{user1} yanlarda {user2} 'yi söylüyor!",
    "{user1}, {user2}! 'ı söylüyor!",
    "{user1}, {user2} 'yi bir iğne ile söylüyor!",
    "{user1}, {user2} 'i bir kalemle söylüyor!",
    "{user1}, {user2} sersemletme tabancasıyla dürtüyor!",
    "{user2} gizlice bir Kürklü!"
    "Hey Herkes! {User1} benden kaba olmamı istiyor!",
    "(･ _ ･) ﾉ ⌒ ● ~ * (･. ･;) <- {kullanıcı2}",
    "Bunu al {user2} \ n (ﾉ ﾟ Д ﾟ) ﾉ))) ● ~ *",
    "Burada {user2} bunu tutun \ n (｀ ・ ω ・) つ ● ~ ＊",
    "(・ _ ・) ノ Ξ ● ~ * {user2} \ nDieeeee !!.",
    "(・ ∀ ・) ｒ 鹵 ~ <≪ 巛; ﾟ Д ﾟ) ﾉ \ n * Böcek spreyleri {user2} *.",
    "(ﾟ Д ﾟ) ﾉ 占 ~ <巛 巛 巛. \ N- {user2} Zararlı!",
    "(う -´) づ ︻╦̵̵̿╤── \ (˚☐˚”) / {user2}. ",
    "{item} ile {user1} {hits} {user2}.",
    "{item} ile karşı karşıya {{user1} {hits} {user2}.",
    "{item} ile bir parça etrafında {user1} {hits} {user2}.",
    "{user1} {user2} 'da bir {item} atar.",
    "{user1} bir {item} yakalar ve {user2} 'nin yüzüne {atar}.",
    "{user1}, {user2} 'ın genel yönünde bir {item} başlattı.",
    "{user1} bir {item} ile {user2} aptalca tokat atmaya başlıyor.",
    "{user1} {user2} 'i iğneliyor ve tekrar tekrar {item} ile {hit} ediyor.",
    "{user1} onunla bir {item} ve {hits} {user2} tutar.",
    "{user1}, {user2} bir sandalyeye bağlanır ve onlara bir {item} atar.",
    "{user1}, {user2} 'da lavda yüzmeyi öğrenmesine yardımcı olmak için dostane bir itici güç verdi.",
    "{user1} zorbalık {user2}.",
    "Nyaan {user2} 'nin bacağını yedi. * Nomnomnom *",
    "{user1} {user2} 'da bir ana top atıyor, direnç boş.",
    "{user1}, bir eylem ışını ile {user2} 'yi vurdu ... bbbbbb (ง ・ ω ・) ง ==== *",
    "{user1} ara ara {kullanıcı2}.",
    "{user1} ora ora'nın {user2}.",
    "{user1} muda muda'nın {user2}.",
    "{user2} bir Jojo referansına dönüştürüldü!",
    "{user1}, {item} ile {user2} 'yi vurdu.",
    "2. Tur! .. Hazır? .. MÜCADELE !!",
    "WhoPixel {user2} 'yi sonsuzluğa ve ötesine taşıyacak.",
    "{user2} bir yarasa yedi ve yeni bir hastalık keşfetti.",
    "{user1}, {user2} bir kağıt düzlemine katlandı",
    "{user1}, {user2} 'ın yaşam gücünü bir fincan çikolatayla değiştirdi.",
    "{user2} bir kaktüs ile 69 yaptı.",
    "{user1} {user2} biraz yarasa çorbası sundu.",
    "{user2} evine, maymunlar gezegenine gönderildi.",
    "{user1}, {user2} adlı kişiyi hareket eden bir trenden attı.",
    "{user1} geleceğe gitti ve {user2} mezarına tükürdü.",
    "{user2} jutsu konuşmasından öldü.",
    "{user2} bir stomp dansı yarışması için halı olarak yerleştirildi. ",
    "{user2} John Wick’in köpeğini yeni öldürdü.",
    "{user1}, {user2} üzerinde bir Avada Kedavra büyüsü yaptı.",
    "{user1}, {user2} 'yi ateşli bir fırına tabi tuttu.",
    "Sakura Haruno artık {user2} 'den daha kullanışlı hale geldi",
    "{user1}, {user2} 'ın yaşam desteğini çıkarttı.",
    "{user1}, 5 yıllık kötü İnternete {user2} abone oldu. ",
    "{user1} bir timsah diş hekimi olmanın neden kötü bir fikir olduğunu öğrendi.",
    "Babamın şakalarından daha kötü olanı biliyor musun? {User2}!",
    "{user1}, {user2} adlı kullanıcının tüm çerezlerini aldı.",
    "{user2} wa mou ....... Shindeiru! - {user1}.",
)

PING_STRING = (
    "PONG!!",
    "Ben Burdayım!",
)

ITEMS = (
    "Demir Döküm tencere",
    "kızgın miyav",
    "kriket sopası",
    "ahşap baston",
    "kürek",
    "tost makinası",
    "kitap",
    "Laptop",
    "plastik tavuk",
    "çivili yarasa",
    "ağır taş",
    "kir yığını",
    "ton tuğla",
    "Rasengan",
    "ruh bombası",
    "100 Tipi Guanyin Pusa",
    "Rasenshuriken",
    "Murasame",
    "Yasak",
    "Chunchunmaru",
    "Kubikiribōchō",
    "Rasengan",
    "küresel uçan kat",
)

THROW = (
    "Atar",
    "Fling'iniz",
    "Aynalar",
    "Fırlatır",
)

HIT = (
   "Hit",
    "Whacks",
    "Tokat",
    "Smacks",
    "Fazla darbe",
    "Okşar",

)

EYES = [
    ['⌐■', '■'],
    [' ͠°', ' °'],
    ['⇀', '↼'],
    ['´• ', ' •`'],
    ['´', '`'],
    ['`', '´'],
    ['ó', 'ò'],
    ['ò', 'ó'],
    ['⸌', '⸍'],
    ['>', '<'],
    ['Ƹ̵̡', 'Ʒ'],
    ['ᗒ', 'ᗕ'],
    ['⟃', '⟄'],
    ['⪧', '⪦'],
    ['⪦', '⪧'],
    ['⪩', '⪨'],
    ['⪨', '⪩'],
    ['⪰', '⪯'],
    ['⫑', '⫒'],
    ['⨴', '⨵'],
    ['⩿', '⪀'],
    ['⩾', '⩽'],
    ['⩺', '⩹'],
    ['⩹', '⩺'],
    ['◥▶', '◀◤'],
    ['◍', '◎'],
    ['/͠-', '┐͡-\\'],
    ['⌣', '⌣”'],
    [' ͡⎚', ' ͡⎚'],
    ['≋'],
    ['૦ઁ'],
    ['  ͯ'],
    ['  ͌'],
    ['ළ'],
    ['◉'],
    ['☉'],
    ['・'],
    ['▰'],
    ['ᵔ'],
    [' ﾟ'],
    ['□'],
    ['☼'],
    ['*'],
    ['`'],
    ['⚆'],
    ['⊜'],
    ['>'],
    ['❍'],
    ['￣'],
    ['─'],
    ['✿'],
    ['•'],
    ['T'],
    ['^'],
    ['ⱺ'],
    ['@'],
    ['ȍ'],
    ['  '],
    ['  '],
    ['x'],
    ['-'],
    ['$'],
    ['Ȍ'],
    ['ʘ'],
    ['Ꝋ'],
    [''],
    ['⸟'],
    ['๏'],
    ['ⴲ'],
    ['◕'],
    ['◔'],
    ['✧'],
    ['■'],
    ['♥'],
    [' ͡°'],
    ['¬'],
    [' º '],
    ['⨶'],
    ['⨱'],
    ['⏓'],
    ['⏒'],
    ['⍜'],
    ['⍤'],
    ['ᚖ'],
    ['ᴗ'],
    ['ಠ'],
    ['σ'],
    ['☯']
]

MOUTHS = [
    ['v'],
    ['ᴥ'],
    ['ᗝ'],
    ['Ѡ'],
    ['ᗜ'],
    ['Ꮂ'],
    ['ᨓ'],
    ['ᨎ'],
    ['ヮ'],
    ['╭͜ʖ╮'],
    [' ͟ل͜'],
    [' ͜ʖ'],
    [' ͟ʖ'],
    [' ʖ̯'],
    ['ω'],
    [' ³'],
    [' ε '],
    ['﹏'],
    ['□'],
    ['ل͜'],
    ['‿'],
    ['╭╮'],
    ['‿‿'],
    ['▾'],
    ['‸'],
    ['Д'],
    ['∀'],
    ['!'],
    ['人'],
    ['.'],
    ['ロ'],
    ['_'],
    ['෴'],
    ['ѽ'],
    ['ഌ'],
    ['⏠'],
    ['⏏'],
    ['⍊'],
    ['⍘'],
    ['ツ'],
    ['益'],
    ['╭∩╮'],
    ['Ĺ̯'],
    ['◡'],
    [' ͜つ']
]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Kafalar",
    "Kuyrukları",
)

DECIDE = (
    "Evet.",
    "Hayır.",
    "Olabilir."
)

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
   "Masalarım bitti, daha fazla sipariş vereceğim.",
    "Git flippin masaları yerine biraz iş yap."
)
